export enum NodeType {
    Branch = "Branch",
    BooleanExpression = "BooleanExpression",
    BooleanExpressionGroup = "BooleanExpressionGroup",
    Aggregate = "Aggregate",
    Operation = "Operation",
    Sequence = "Sequence",
    FunctionCall = "FunctionCall",
    PropertyAccess = "PropertyAccess",
    IndexAccess = "IndexAccess",
    Identifier = "Identifier",
    StringLiteral = "StringLiteral",
    NumericLiteral = "NumericLiteral",
    BooleanLiteral = "BooleanLiteral",
    ForLoop = "ForLoop",
    Object = "Object",
    ObjectProperty = "ObjectProperty",
    StringConcatenation = "StringConcatenation",
}